# Generated by Django 3.1 on 2020-08-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_file', models.FileField(upload_to='texts/')),
                ('doc_type', models.CharField(max_length=20)),
                ('discussion_topic', models.CharField(max_length=100)),
                ('note_title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('created', models.CharField(max_length=100)),
                ('scaffolds', models.CharField(max_length=120)),
                ('keywords', models.CharField(max_length=100)),
                ('views', models.CharField(max_length=100)),
                ('buildson', models.CharField(max_length=100)),
                ('edit_by', models.CharField(max_length=100)),
                ('read_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Docs',
            },
        ),
        migrations.CreateModel(
            name='LAToolType',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('la_tool_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LAToolType',
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'SiteUser',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=255)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SentimentLA.latooltype')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SentimentLA.siteuser')),
            ],
            options={
                'db_table': 'APIKey',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('input_text_id', models.IntegerField()),
                ('input_text_type', models.CharField(max_length=100)),
                ('result_id', models.CharField(max_length=100)),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SentimentLA.latooltype')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SentimentLA.siteuser')),
            ],
            options={
                'db_table': 'Analysis',
            },
        ),
    ]
