# Generated by Django 3.1 on 2020-08-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentLA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_File',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_file', models.FileField(upload_to='texts/')),
            ],
            options={
                'db_table': 'Doc_File',
            },
        ),
    ]
