# Generated by Django 3.1 on 2020-09-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentLA', '0002_doc_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc_file',
            old_name='doc_id',
            new_name='did',
        ),
        migrations.RemoveField(
            model_name='doc_file',
            name='doc_file',
        ),
        migrations.AddField(
            model_name='doc_file',
            name='file',
            field=models.FileField(default=123, upload_to='SAFiles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc_file',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc_file',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SentimentLA.siteuser'),
            preserve_default=False,
        ),
    ]
